// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<int>("CountOfPages")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpdatedUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "About",
                            CountOfPages = 2,
                            CreatedTime = new DateTime(2022, 11, 25, 19, 42, 15, 341, DateTimeKind.Utc).AddTicks(6982),
                            CreatedUserId = 1,
                            ImagePath = "~/images/product/book-1.png",
                            Name = "Book-1",
                            Price = 5.0,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = 0
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpdatedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2022, 11, 25, 19, 42, 15, 341, DateTimeKind.Utc).AddTicks(6265),
                            CreatedTime = new DateTime(2022, 11, 25, 19, 42, 15, 341, DateTimeKind.Utc).AddTicks(6854),
                            CreatedUserId = 1,
                            Email = "admin@gmail.com",
                            FullName = "AdminAdmin",
                            Hash = "�$3\"�qw>+��Z��\"sySle�P:�*?�",
                            Salt = "+jlsinWbE3KkexaI8iqZ0WurgYE3ELg20HlojwEhnVv+h7QlL28jj7vFcSFAIKfDEoW/GQq8v+0wTmyKws1k59HZTfFul/SUxZ0QdJSZdjloqE4yAuGu0ByIKYA0aVZq7jXAEPDf3Q6sSL4LtRKIV/0Tn+YcylZ+koxwTlWv1145YUu1FX6+m18EnnijJJTzGxdoRIp5odH2fcq+AcPCI/8geDIS2AoIGhNPacuwKwxGbJdIrmYLkx98YKFYQfjDbJX1Wd8BGyHgPNDkFhGfcQahy4zTndQcywPZTXIYY6M2zzRZ3E5JBPPcn3cSPVM9HNhy8IUE11ZnOj4KBdv8",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = 0,
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
